FROM python:3.10-buster

WORKDIR /code

COPY requirements.txt .
COPY cron /code/cron/

ADD cron/crontab /etc/cron.d/hamfurs
RUN chmod 0644 /etc/cron.d/hamfurs

RUN touch /var/log/cron.log

#Install Cron
RUN apt-get update
RUN apt-get -y install cron

RUN pip install --upgrade pip wheel
RUN pip install -r requirements.txt

CMD cron && sleep infinity

